class Solution:
    def freqAlphabets(self, s: str) -> str:
        a = s.replace('26#','z')
        b = a.replace('25#','y')
        c = b.replace('24#','x')
        d = c.replace('23#','w')
        e = d.replace('22#','v')
        f = e.replace('21#','u')
        g = f.replace('20#','t')
        h = g.replace('19#','s')
        i = h.replace('18#','r')
        j = i.replace('17#','q')
        k = j.replace('16#','p')
        l = k.replace('15#','o')
        m = l.replace('14#','n')
        n = m.replace('13#','m')
        o = n.replace('12#','l')
        p = o.replace('11#','k')
        q = p.replace('10#','j')
        r = q.replace('9','i')
        S = r.replace('8','h')
        t = S.replace('7','g')
        u = t.replace('6','f')
        v = u.replace('5','e')
        w = v.replace('4','d')
        x = w.replace('3','c')
        y = x.replace('2','b')
        z = y.replace('1','a')
        return z